from .infinite_sampler_v7 import NODE_CLASS_MAPPINGS as _N7, NODE_DISPLAY_NAME_MAPPINGS as _D7
from .muse_director_v1 import NODE_CLASS_MAPPINGS as _NM1, NODE_DISPLAY_NAME_MAPPINGS as _DM1
from .muse_guide import NODE_CLASS_MAPPINGS as _NMG, NODE_DISPLAY_NAME_MAPPINGS as _DMG

NODE_CLASS_MAPPINGS = {**_N7, **_NM1, **_NMG}
NODE_DISPLAY_NAME_MAPPINGS = {**_D7, **_DM1, **_DMG}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
